### ISSUE TITLE
get_norm()

### ISSUE THREAD

**Issue by Exlonk** [ifilot/pyqint#34]
gto.get_norm() doesn't work

![image](https://github.com/ifilot/pyqint/assets/81200520/cb4d90bb-156d-4938-bc28-f685b0f1d543)

**Comment by Exlonk** [comment]
pdt: I love your module. Best wishes

**Comment by ifilot** [comment]
Thank you for reporting this error! This bug has been resolved in version 0.16.2. Happy computing!
