### ISSUE TITLE
spherical gaussian type orbitals

### ISSUE THREAD

**Issue by moritzgubler** [ifilot/pyqint#38]
Hi

Thanks for developing and maintaining this nice code. I really enjoy using it. I don't know if this is the right place to ask, if not, please let me know.

Is there an easy way to convert the cartesian Gaussian type orbitals to spherical Gaussian type orbitals or is this not part of this library? I could not find anything in the documentation.

Thanks a lot for your help.

**Comment by ifilot** [comment]
Hello! This is certainly the right place to ask questions. You can even set a "question" label to any issue if you want to.

To answer your question: I have not (yet) implemented any functionality to convert the cartesian Gaussian type orbitals to a spherical version. Nevertheless, once you know the result in the cartesian basis, you can convert it to a spherical one using a linear transformation. The details are provided in this [paper](https://onlinelibrary.wiley.com/doi/10.1002/qua.560540202).

**Comment by moritzgubler** [comment]
Thanks for your answer, I am definitely looking forward to that feature. In the mean time, I can build something with the reference you mentioned.
