### ISSUE TITLE
pip install pyqint Not Working

### ISSUE THREAD

**Issue by emilyrobertskang** [ifilot/pyqint#5]
When I type:

`pip install pyqint`

In my command line, I get the following error message:

```
ERROR: Could not find a version that satisfies the requirement pyqint (from versions: none)
ERROR: No matching distribution found for pyqint
```

In seems to work when I install via conda 

I get the message:
```
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.
```
But then when I try to execute my script I get the message:
` from pyqint import PyQInt, Molecule
ModuleNotFoundError: No module named 'pyqint'`

I'm using Python 3.9.2 on a Windows machine.

**Comment by ifilot** [comment]
I have only tested PyQInt for Python version 3.8, which is the default version shipped with Anaconda. I was under the anticipation that newer versions of Python would be backward compatible to 3.8, but apparently this is not the case.

I'll see if I can upgrade to 3.9.2 on my Windows machine and see if I can reproduce and possible fix the problem.

**Comment by ifilot** [comment]
Apologies for only realizing that I never gave an update on this, but this issue is now fixed (already several versions of the program ago).
