### ISSUE TITLE
conda install -c ifilot pyqint Not Working

### ISSUE THREAD

**Issue by paramnaik** [ifilot/pyqint#6]
I downloaded the installer.exe correctly and when I type the given command in Anaconda Prompt, it gives the attached error notice. 

![Anaconda Error 3](https://user-images.githubusercontent.com/94965064/143224162-cbfec44c-bf79-4f5d-863b-8e8a82507cb2.jpg)

**Comment by ifilot** [comment]
Thank you for bringing this to my attention. I have recompiled the source code using Python 3.9 and uploaded the package to the repository. It should be working now.
